# name: Todoist Readme

# on:
#   workflow_dispatch:
#   schedule:
#     # Runs every hour
#     - cron: "0 * * * *"

# jobs:
#   update-readme:
#     name: Update todoist stats
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: chinshunyu/todoist-readme@master
#         with:
#           TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
#           PREMIUM: ""


name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""

      # 新增步骤来推送更改
      - name: Commit and Push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Todoist updated."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
