name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # - cron: "30 18 * * *"
    - cron: "30 3,7,10,14,15 * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chinshunyu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""